### ISSUE TITLE
Angular path

### ISSUE THREAD

**Issue by jbonigomes** [learnapollo/learnapollo#18]
Great project, this is just a question, does LearnApollo already support the Angular.js learning path?

**Comment by marktani** [comment]
Hey, we initially planned to have an Angular path, but currently lack contributors with the required knowledge/time. Feel free to join [our Slack](http://slack.graph.cool) if you want to chat more about this :slightly_smiling_face:

**Comment by jbonigomes** [comment]
thanks @marktani

**Comment by marktani** [comment]
Hey @jbonigomes, I just finished a small playground app for the pokedex.

It's basically comparable to the end of the third exercise of the React track for example :slightly_smiling_face: 

https://www.learnapollo.com/tutorial-angular/angular-playground

**Comment by jbonigomes** [comment]
Thanks @marktani this is a really good example
