### ISSUE TITLE
As a user, I can check the solution of the first step "Install Apollo" on react native project

### ISSUE THREAD

**Issue by tychota** [learnapollo/learnapollo#3]

**Comment by tychota** [comment]
@schickling: https://github.com/learnapollo/pokedex-react-native/commit/843a9d5ba694be93bf9ed8b0f270d157669cafce

Can you give me feeedback, if all clear, lets close this :)

**Comment by schickling** [comment]
LGTM but I don't have too much experience with RN myself. Maybe @stubailo could take a quick look?

**Comment by stubailo** [comment]
Seems reasonable.
