### ISSUE TITLE
Possible Excursion: CSS Syntax

### ISSUE THREAD

**Issue by hammannja** [learnapollo/learnapollo#41]
Loved the React Tutorial!

In the tutorial, you use syntax like: className='link dim grow mw4 bg-white ma2 pa3 shadow-1'

Could you do an Excursion on these css short-names and provide some reference information so that the reader can understand what terms like "ma2" and "pa3" mean?

Thanks!

**Comment by marktani** [comment]
Hey @hammannja thanks for your suggestion. While I think an excursion like this is out-of-scope, these styles come from [tachyons](tachyons.io). Hope that helps :)
