### ISSUE TITLE
Remove side effect in render

### ISSUE THREAD

**Issue by globalchubby** [learnapollo/learnapollo#51]
https://github.com/learnapollo/learnapollo/blame/master/content/tutorial-react/react-07.md#L157

`render` here has a side effect that modifies that application state - namely, it changes the current route. I think a better way to handle this would be in a `react-router` `onEnter` hook. At least, I'd recommend calling out in a comment that this isn't a best practices, but suffices for the purposes of the tutorial.

Thanks for the great work!

**Comment by marktani** [comment]
Thanks for the suggestion! A PR [here](https://github.com/learnapollo/pokedex-react/blob/master/exercise-07-solution/src/components/Pokedex.js#L56-L61) would be appreciated! :slightly_smiling_face:

**Comment by globalchubby** [comment]
By the way I noticed in https://www.graph.cool/docs/faq/graphcool-technology-ul6ue9gait:

>Frontend: We use React, Relay and TypeScript 2 for our console and make this project available as open-source here. We have several other packages that we use internally as open-source, such as babel-plugin-react-relay, graphql-config or prep.

Are you guys still using Relay, or `react-apollo` now?

**Comment by marktani** [comment]
Hey, thanks for the question! We use Relay, for example in our [Console](https://github.com/graphcool/console/) but we're also using Apollo in different projects like our [homepage](https://github.com/graphcool/homepage). Happy to discuss more questions in [Slack](https://slack.graph.cool).
