### ISSUE TITLE
Atom editor complains about missing eslint-plugin-flowtype

### ISSUE THREAD

**Issue by cideM** [learnapollo/learnapollo#54]
The ESLint plugins from `react-scripts` are not listed as dependencies in `package.json` and are never installed on my system when running `npm i`

**Comment by marktani** [comment]
What would that dependencies be? A PR would be highly appreciated :slightly_smiling_face:

**Comment by cideM** [comment]
I digged a bit deeper and it's actually a problem with https://github.com/learnapollo/pokedex-react. It's not easily fixed as it has to do with the way `react-scripts` hides dependencies for its ESLint in `node_modules/react-scripts/config/eslint.js`. It's the same bug that Atom users have with `create-react-app`, which is addressed [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor). So this issue can be closed as it's something that is under development in https://github.com/eslint/eslint/issues/3458

Oh and the missing dependencies are from `plugins: [/*'import', */'flowtype', 'jsx-a11y', 'react'],` in `node_modules/react-scripts/config/eslint.js` so:

- eslint-plugin-flowtype
- eslint-plugin-jsx-a11y
- eslint-plugin-react

**Comment by marktani** [comment]
Wow thanks for the digging! 

> So this issue can be closed as it's something that is under development in eslint/eslint#3458

Done!
