### ISSUE TITLE
exercize-03, dependencies

### ISSUE THREAD

**Issue by jacklinton** [learnapollo/learnapollo#67]
I had to add "react-native-experimental-navigation": "0.26.10", to the dependencies to get this to work because there is apparently a bug in 0.26.11 and it throws an error that style "left" is not supported in native animated, or something to that effect.

**Comment by jacklinton** [comment]
This is for the react-native version of the tutorial. Whenever you tap on one of the pokemon you get an error and you can't navigate to the pokemon pages.

**Comment by jacklinton** [comment]
I forked the project and submitted a pull request with the updated package.json files.

**Comment by marktani** [comment]
Thanks so much, I merged it: https://github.com/learnapollo/pokedex-react-native/pull/5
