### ISSUE TITLE
Exercize-04 react-native, can't find variable error

### ISSUE THREAD

**Issue by jacklinton** [learnapollo/learnapollo#68]
The user of the tutorial must import { pokemonCardFragments } from './PokemonCard' in their PokemonPage.js file in order to get the program to work. It would be helpful to mention it somewhere in the tutorial.

Here is the page https://www.learnapollo.com/tutorial-react-native/react-native-04.

**Comment by jacklinton** [comment]
Edited the page and submitted a pull request.

**Comment by marktani** [comment]
Thanks, it's merged: https://github.com/learnapollo/learnapollo/pull/69/ 🙌
