### ISSUE TITLE
Doubt: Removing Trainer Section in AddPokemonCard.js After Adding forcefetch field in Pokedex.js

### ISSUE THREAD

**Issue by gdad-s-river** [learnapollo/learnapollo#70]
In the tutorial it is written that after adding 

```
// Pokedex.js

const PokedexWithData = graphql(TrainerQuery, {
  options: {
    variables: {
      name: 'Arihant Verma '
    },
    forceFetch: true,  <---- # this
  }
}
)(Pokedex)
```

Why could we remove 

```
// AddPokemonCard.js

const createPokemonMutation = gql`
  mutation createPokemon($name: String!, $url: String!, $trainerId: ID) {
    createPokemon(name: $name, url: $url, trainerId: $trainerId) {
      trainer {     <---- # this trainer section
        id
        ownedPokemons {
          id
        }
      }
    }
  }
`
```

and replace it just with `id`. 

Doubt 1: Earlier we had to explicitly tell that we wanted to fetch trainer object after mutation is done, what is being returned now, with only `id` being returned after mutation?  What does it exactly mean?

It's written for the trainer object that

> What this does, is telling Apollo Client to refetch the trainer object and all its related pokemons whenever we create a new pokemon. Apollo Store identifies the trainer object by its id and it basically merges the known pokemons with all the pokemons in the mutation response. Even though this is highly inefficient, this works in our example.

Doubt 2:  Does the above holds true only after we have added `dataIdFromObject: o => o.id` in ApoloClient instantiation ?

**Comment by marktani** [comment]
> Doubt 2: Does the above holds true only after we have added dataIdFromObject: o => o.id in ApoloClient instantiation ?

Yes :slightly_smiling_face: 

Before, we would query not only the newly created pokemon id, but actually the trainer and all the pokemon he owns. By adding the `forceFetch` option (this is by the way renamed to `forcePolicy` in the latest Apollo version), we are querying the whole trainer whenever we visit the route again.

Hope that helps! I tried to explain it in more detail in this excursion: https://www.learnapollo.com/excursions/excursion-02/

**Comment by gdad-s-river** [comment]
Thanks, @marktani, this is helpful! Understood everything now :)
