### ISSUE TITLE
API contents not created

### ISSUE THREAD

**Issue by coproduto** [learnapollo/learnapollo#81]
When starting the React track, I logged in with Github, downloaded the files as requested in the tutorial, got my endpoint: https://api.graph.cool/simple/v1/cj3n46i1777ou01732xhk4q6q and started running the examples. 

I had no issues at first, but as soon as I got to the second lesson (https://www.learnapollo.com/tutorial-react/react-02) and tried to query for my "Trainer" entry, I realized the server would always return ```null```. It seems that for some reason no entities have been created in my API instance.

This is confirmed by trying to run queries using GraphiQL - all queries return ```null```.

**Comment by marktani** [comment]
Hey @pcstl, when did you log in with Github? Could you try this: https://github.com/learnapollo/learnapollo/issues/79#issuecomment-306420452?

**Comment by coproduto** [comment]
Hello @marktani.

I logged in earlier today, around 1 PM (GMT-3).

I just tried following the steps described in #79 :

1. Revoked LearnApollo's authorization
2. Logged out of Github
3. Logged into LearnApollo

However, it kept giving me the same endpoint. I then tried this in an incognito window so I could be sure there wouldn't be any cookie or localStorage-related issues:

1. Opened LearnApollo. Instead of the endpoint, the prompt to log into GitHub showed up.
2. Logged into GitHub. 
3. Was redirected back to LearnApollo.

However... It gave me the exact same endpoint as before, and the issue persists. I have reproduced the issue here: https://api.graph.cool/simple/v1/cj3n46i1777ou01732xhk4q6q?query=query%20%7B%0A%20%20Trainer(name%3A%20%22Pedro%20Castilho%22)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A

**Comment by coproduto** [comment]
https://api.graph.cool/simple/v1/cj3n46i1777ou01732xhk4q6q?query=query%20%7B%0A%20%20allTrainers(first%3A%2010)%20%7B%0A%20%20%20%20name%0A%20%20%7D%0A%7D%0A

Here you can see that there are no Trainers created.

**Comment by marktani** [comment]
Hey @pcstl, could you please contact me in [Slack](https://slack.graph.cool). My handle there is @nilan.

**Comment by marktani** [comment]
Closing this issue. See above for anyone that runs into this again 🙂
