### ISSUE TITLE
Issue Loading Trainer Data, Exercise 2

### ISSUE THREAD

**Issue by ramyanaga** [learnapollo/learnapollo#82]
I signed in through Github before downloading files, but when I run the custom-made TrainerQuery:
`Trainer(name: "ramyanaga.99@gmail.com") {
    name
  }`
the response returns null.

**Comment by marktani** [comment]
Could you and everyone else that is running into this issue please contact me in [Slack](https://slack.graph.cool)? My handle there is @nilan.

**Comment by marktani** [comment]
Closing this issue. See above for anyone that runs into this again 🙂
