### ISSUE TITLE
Reflect that name will be injected when authenticated

### ISSUE THREAD

**Issue by schickling** [learnapollo/learnapollo#9]
![image](https://cloud.githubusercontent.com/assets/1567498/20455099/84461860-ae53-11e6-86c4-12217a62f90b.png)

**Comment by marktani** [comment]
I have to refresh the page after clicking "next" to replace `__NAME__`

![la-basic-queries](https://cloud.githubusercontent.com/assets/1780597/20456232/7364551a-ae72-11e6-8097-8cab4b5cfb51.png)
