### ISSUE TITLE
Fix CORS

### ISSUE THREAD

**Issue by HaNdTriX** [learnapollo/learnapollo#91]
Currently the login all over the app is broken.

![screenie](https://user-images.githubusercontent.com/1265681/30100056-d63d4354-92e7-11e7-9af8-6393529ef371.jpg)

**Browser:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36`

**Comment by eugenegodun** [comment]
The same for me.

**Comment by marktani** [comment]
Hey there, the Learn Apollo tutorial has been deprecated 🙂  Please check https://www.howtographql.com/ instead.

**Comment by eugenegodun** [comment]
@marktani  https://www.howtographql.com/  has a lot of unresolved issues too 👎

**Comment by marktani** [comment]
Similar to Learn Apollo, How to GraphQL is a community initiative that thrives on support from the community 🙂 

Community contributions have been great so far, and we are continuously looking at issues and PRs.

Feel free to ping me [in Slack](slack.graph.cool) (my handle is @nilan) if you run into a specific problem with HTG, I'd love to help you out!
